/*
 * Copyright (c) 2020, Infosys Ltd.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
 /******************************************************************************
 *
 * This is an auto generated file.
 * Please do not edit this file.
 * All edits to be made through template source file
 * <TOP-DIR/scripts/GtpV2StackCodeGen/tts/ietemplate.h.tt>
 ******************************************************************************/
#ifndef BEARERTFTIE_H_
#define BEARERTFTIE_H_

#include "manual/gtpV2Ie.h"



class BearerTftIe: public GtpV2Ie {
public:
    BearerTftIe();
    virtual ~BearerTftIe();

    bool encodeBearerTftIe(MsgBuffer &buffer,
                 BearerTftIeData const &data);
    bool decodeBearerTftIe(MsgBuffer &buffer,
                 BearerTftIeData &data, Uint16 length);
    void displayBearerTftIe_v(BearerTftIeData const &data,
                 Debug &stream);
};

#endif /* BEARERTFTIE_H_ */
