/*
 * Copyright (c) 2020, Infosys Ltd.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
 /******************************************************************************
 *
 * This is an auto generated file.
 * Please do not edit this file.
 * All edits to be made through template source file
 * <TOP-DIR/scripts/GtpV2StackCodeGen/tts/ietemplate.h.tt>
 ******************************************************************************/
#ifndef COMPLETEREQUESTMESSAGEIE_H_
#define COMPLETEREQUESTMESSAGEIE_H_

#include "manual/gtpV2Ie.h"



class CompleteRequestMessageIe: public GtpV2Ie {
public:
    CompleteRequestMessageIe();
    virtual ~CompleteRequestMessageIe();

    bool encodeCompleteRequestMessageIe(MsgBuffer &buffer,
                 CompleteRequestMessageIeData const &data);
    bool decodeCompleteRequestMessageIe(MsgBuffer &buffer,
                 CompleteRequestMessageIeData &data, Uint16 length);
    void displayCompleteRequestMessageIe_v(CompleteRequestMessageIeData const &data,
                 Debug &stream);
};

#endif /* COMPLETEREQUESTMESSAGEIE_H_ */
