/*
 * Copyright (c) 2020, Infosys Ltd.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
 /******************************************************************************
 *
 * This is an auto generated file.
 * Please do not edit this file.
 * All edits to be made through template source file
 * <TOP-DIR/scripts/GtpV2StackCodeGen/tts/ietemplate.h.tt>
 ******************************************************************************/
#ifndef GUTIIE_H_
#define GUTIIE_H_

#include "manual/gtpV2Ie.h"



class GutiIe: public GtpV2Ie {
public:
    GutiIe();
    virtual ~GutiIe();

    bool encodeGutiIe(MsgBuffer &buffer,
                 GutiIeData const &data);
    bool decodeGutiIe(MsgBuffer &buffer,
                 GutiIeData &data, Uint16 length);
    void displayGutiIe_v(GutiIeData const &data,
                 Debug &stream);
};

#endif /* GUTIIE_H_ */
