/*
 * Copyright 2019-present Infosys Limited
 *
 * SPDX-License-Identifier: Apache-2.0
 */
/******************************************************************************
 *
 * This is an auto generated file.
 * Please do not edit this file.
 * All edits to be made through template source file
 * <TOP-DIR/scripts/GtpV2StackCodeGen/tts/ietemplate.cpp.tt>
 ******************************************************************************/

#include "plmnIdIe.h"
#include "dataTypeCodecUtils.h"

PlmnIdIe::PlmnIdIe() 
{
    ieType = 120;
    // TODO

}

PlmnIdIe::~PlmnIdIe() {
    // TODO Auto-generated destructor stub
}

bool PlmnIdIe::encodePlmnIdIe(MsgBuffer &buffer, PlmnIdIeData const &data)
{
    if (!(buffer.writeUint8(data.plmnId)))
    {
        errorStream.add((char *)"Encoding of plmnId failed\n");
        return false;
    }

    return true;
}

bool PlmnIdIe::decodePlmnIdIe(MsgBuffer &buffer, PlmnIdIeData &data, Uint16 length)
{     
    // TODO optimize the length checks
    
    Uint16 ieBoundary = buffer.getCurrentIndex() + length;

    buffer.readUint8(data.plmnId);
    if (buffer.getCurrentIndex() > ieBoundary)
    {
        errorStream.add((char *)"Attempt to read beyond IE boundary: plmnId\n");
        return false;
    }

    // The IE is decoded now. The buffer index should be pointing to the 
    // IE Boundary. If not, we have some more data left for the IE which we don't know
    // how to decode
    if (ieBoundary == buffer.getCurrentIndex())
    {
        return true;
    }
    else
    {
        errorStream.add((char *)"Unable to decode IE PlmnIdIe\n");
        return false;
    }
}
void PlmnIdIe::displayPlmnIdIe_v(PlmnIdIeData const &data, Debug &stream)
{
    stream.incrIndent();
    stream.add((char *)"PlmnIdIeData:");
    stream.incrIndent();
    stream.endOfLine();
  
    stream.add((char *)"plmnId: ");
    stream.add(data.plmnId);
    stream.endOfLine();
    stream.decrIndent();
    stream.decrIndent();
}
