/*
 * Copyright (c) 2020, Infosys Ltd.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
 /******************************************************************************
 *
 * This is an auto generated file.
 * Please do not edit this file.
 * All edits to be made through template source file
 * <TOP-DIR/scripts/GtpV2StackCodeGen/tts/ietemplate.h.tt>
 ******************************************************************************/
#ifndef RANNASCAUSEIE_H_
#define RANNASCAUSEIE_H_

#include "manual/gtpV2Ie.h"



class RanNasCauseIe: public GtpV2Ie {
public:
    RanNasCauseIe();
    virtual ~RanNasCauseIe();

    bool encodeRanNasCauseIe(MsgBuffer &buffer,
                 RanNasCauseIeData const &data);
    bool decodeRanNasCauseIe(MsgBuffer &buffer,
                 RanNasCauseIeData &data, Uint16 length);
    void displayRanNasCauseIe_v(RanNasCauseIeData const &data,
                 Debug &stream);
};

#endif /* RANNASCAUSEIE_H_ */
