/*
 * Copyright (c) 2020, Infosys Ltd.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
 /******************************************************************************
 *
 * This is an auto generated file.
 * Please do not edit this file.
 * All edits to be made through template source file
 * <TOP-DIR/scripts/GtpV2StackCodeGen/tts/ietemplate.h.tt>
 ******************************************************************************/
#ifndef RECOVERYIE_H_
#define RECOVERYIE_H_

#include "manual/gtpV2Ie.h"



class RecoveryIe: public GtpV2Ie {
public:
    RecoveryIe();
    virtual ~RecoveryIe();

    bool encodeRecoveryIe(MsgBuffer &buffer,
                 RecoveryIeData const &data);
    bool decodeRecoveryIe(MsgBuffer &buffer,
                 RecoveryIeData &data, Uint16 length);
    void displayRecoveryIe_v(RecoveryIeData const &data,
                 Debug &stream);
};

#endif /* RECOVERYIE_H_ */
