/*
 * Copyright (c) 2020, Infosys Ltd.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
 /******************************************************************************
 *
 * This is an auto generated file.
 * Please do not edit this file.
 * All edits to be made through template source file
 * <TOP-DIR/scripts/GtpV2StackCodeGen/tts/ietemplate.h.tt>
 ******************************************************************************/
#ifndef SEQUENCENUMBERIE_H_
#define SEQUENCENUMBERIE_H_

#include "manual/gtpV2Ie.h"



class SequenceNumberIe: public GtpV2Ie {
public:
    SequenceNumberIe();
    virtual ~SequenceNumberIe();

    bool encodeSequenceNumberIe(MsgBuffer &buffer,
                 SequenceNumberIeData const &data);
    bool decodeSequenceNumberIe(MsgBuffer &buffer,
                 SequenceNumberIeData &data, Uint16 length);
    void displaySequenceNumberIe_v(SequenceNumberIeData const &data,
                 Debug &stream);
};

#endif /* SEQUENCENUMBERIE_H_ */
