/*
 * Copyright (c) 2020, Infosys Ltd.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
 /******************************************************************************
 *
 * This is an auto generated file.
 * Please do not edit this file.
 * All edits to be made through template source file
 * <TOP-DIR/scripts/GtpV2StackCodeGen/tts/ietemplate.h.tt>
 ******************************************************************************/
#ifndef TARGETIDENTIFICATIONIE_H_
#define TARGETIDENTIFICATIONIE_H_

#include "manual/gtpV2Ie.h"



class TargetIdentificationIe: public GtpV2Ie {
public:
    TargetIdentificationIe();
    virtual ~TargetIdentificationIe();

    bool encodeTargetIdentificationIe(MsgBuffer &buffer,
                 TargetIdentificationIeData const &data);
    bool decodeTargetIdentificationIe(MsgBuffer &buffer,
                 TargetIdentificationIeData &data, Uint16 length);
    void displayTargetIdentificationIe_v(TargetIdentificationIeData const &data,
                 Debug &stream);
};

#endif /* TARGETIDENTIFICATIONIE_H_ */
