/*
 * Copyright 2020-present Infosys Limited
 *
 * SPDX-License-Identifier: Apache-2.0
 */
 
 /******************************************************
 * attachWfIdentityResponse.h
 * This is an auto generated file.
 * Please do not edit this file.
 * All edits to be made through template source file
 * <TOP-DIR/scripts/SMCodeGen/templates/stateMachineTmpls/state.h.tt>
 ******************************************************/
 
#ifndef __AttachWfIdentityResponse__
#define __AttachWfIdentityResponse__

#include "state.h"

namespace mme {

	class AttachWfIdentityResponse : public SM::State
	{
		public:
			/******************************************
			* Instance 
			*    Creates static instance for the state
			*******************************************/
			static AttachWfIdentityResponse* Instance();

			/****************************************
			* AttachWfIdentityResponse
			*    Destructor
			****************************************/
			~AttachWfIdentityResponse();			
			
			/******************************************
			* initialize
			*  Initializes action handlers for the state
			* and next state
			******************************************/
			void initialize();
	
		private:
			/****************************************
			* AttachWfIdentityResponse
			*    Private constructor
			****************************************/
			AttachWfIdentityResponse();  
	};
};
#endif // __AttachWfIdentityResponse__
