/*
 * Copyright 2020-present Infosys Limited
 *
 * SPDX-License-Identifier: Apache-2.0
 */
 
 /******************************************************
 * attachWfSecCmp.h
 * This is an auto generated file.
 * Please do not edit this file.
 * All edits to be made through template source file
 * <TOP-DIR/scripts/SMCodeGen/templates/stateMachineTmpls/state.h.tt>
 ******************************************************/
 
#ifndef __AttachWfSecCmp__
#define __AttachWfSecCmp__

#include "state.h"

namespace mme {

	class AttachWfSecCmp : public SM::State
	{
		public:
			/******************************************
			* Instance 
			*    Creates static instance for the state
			*******************************************/
			static AttachWfSecCmp* Instance();

			/****************************************
			* AttachWfSecCmp
			*    Destructor
			****************************************/
			~AttachWfSecCmp();			
			
			/******************************************
			* initialize
			*  Initializes action handlers for the state
			* and next state
			******************************************/
			void initialize();
	
		private:
			/****************************************
			* AttachWfSecCmp
			*    Private constructor
			****************************************/
			AttachWfSecCmp();  
	};
};
#endif // __AttachWfSecCmp__
