/*
 * Copyright 2020-present Infosys Limited
 *
 * SPDX-License-Identifier: Apache-2.0
 */
 
 /******************************************************
 * attachWfCsResp.h
 * This is an auto generated file.
 * Please do not edit this file.
 * All edits to be made through template source file
 * <TOP-DIR/scripts/SMCodeGen/templates/stateMachineTmpls/state.h.tt>
 ******************************************************/
 
#ifndef __AttachWfCsResp__
#define __AttachWfCsResp__

#include "state.h"

namespace mme {

	class AttachWfCsResp : public SM::State
	{
		public:
			/******************************************
			* Instance 
			*    Creates static instance for the state
			*******************************************/
			static AttachWfCsResp* Instance();

			/****************************************
			* AttachWfCsResp
			*    Destructor
			****************************************/
			~AttachWfCsResp();			
			
			/******************************************
			* initialize
			*  Initializes action handlers for the state
			* and next state
			******************************************/
			void initialize();
	
		private:
			/****************************************
			* AttachWfCsResp
			*    Private constructor
			****************************************/
			AttachWfCsResp();  
	};
};
#endif // __AttachWfCsResp__
