/*
 * Copyright 2020-present Infosys Limited
 *
 * SPDX-License-Identifier: Apache-2.0
 */
 
 /******************************************************
 * dedDeactStart.h
 * This is an auto generated file.
 * Please do not edit this file.
 * All edits to be made through template source file
 * <TOP-DIR/scripts/SMCodeGen/templates/stateMachineTmpls/state.h.tt>
 ******************************************************/
 
#ifndef __DedDeactStart__
#define __DedDeactStart__

#include "state.h"

namespace mme {

	class DedDeactStart : public SM::State
	{
		public:
			/******************************************
			* Instance 
			*    Creates static instance for the state
			*******************************************/
			static DedDeactStart* Instance();

			/****************************************
			* DedDeactStart
			*    Destructor
			****************************************/
			~DedDeactStart();			
			
			/******************************************
			* initialize
			*  Initializes action handlers for the state
			* and next state
			******************************************/
			void initialize();
	
		private:
			/****************************************
			* DedDeactStart
			*    Private constructor
			****************************************/
			DedDeactStart();  
	};
};
#endif // __DedDeactStart__
