/*
 * Copyright 2020-present Infosys Limited
 *
 * SPDX-License-Identifier: Apache-2.0
 */
 
 /******************************************************
 * dedDeactWfBearerTearup.h
 * This is an auto generated file.
 * Please do not edit this file.
 * All edits to be made through template source file
 * <TOP-DIR/scripts/SMCodeGen/templates/stateMachineTmpls/state.h.tt>
 ******************************************************/
 
#ifndef __DedDeactWfBearerTearup__
#define __DedDeactWfBearerTearup__

#include "state.h"

namespace mme {

	class DedDeactWfBearerTearup : public SM::State
	{
		public:
			/******************************************
			* Instance 
			*    Creates static instance for the state
			*******************************************/
			static DedDeactWfBearerTearup* Instance();

			/****************************************
			* DedDeactWfBearerTearup
			*    Destructor
			****************************************/
			~DedDeactWfBearerTearup();			
			
			/******************************************
			* initialize
			*  Initializes action handlers for the state
			* and next state
			******************************************/
			void initialize();
	
		private:
			/****************************************
			* DedDeactWfBearerTearup
			*    Private constructor
			****************************************/
			DedDeactWfBearerTearup();  
	};
};
#endif // __DedDeactWfBearerTearup__
