/*
 * Copyright 2020-present Infosys Limited
 *
 * SPDX-License-Identifier: Apache-2.0
 */
 
 /******************************************************
 * erabModIndStart.h
 * This is an auto generated file.
 * Please do not edit this file.
 * All edits to be made through template source file
 * <TOP-DIR/scripts/SMCodeGen/templates/stateMachineTmpls/state.h.tt>
 ******************************************************/
 
#ifndef __ErabModIndStart__
#define __ErabModIndStart__

#include "state.h"

namespace mme {

	class ErabModIndStart : public SM::State
	{
		public:
			/******************************************
			* Instance 
			*    Creates static instance for the state
			*******************************************/
			static ErabModIndStart* Instance();

			/****************************************
			* ErabModIndStart
			*    Destructor
			****************************************/
			~ErabModIndStart();			
			
			/******************************************
			* initialize
			*  Initializes action handlers for the state
			* and next state
			******************************************/
			void initialize();
	
		private:
			/****************************************
			* ErabModIndStart
			*    Private constructor
			****************************************/
			ErabModIndStart();  
	};
};
#endif // __ErabModIndStart__
