/*
 * Copyright 2020-present Infosys Limited
 *
 * SPDX-License-Identifier: Apache-2.0
 */
 
 /******************************************************
 * niDetachWfDetAccptDelSessResp.h
 * This is an auto generated file.
 * Please do not edit this file.
 * All edits to be made through template source file
 * <TOP-DIR/scripts/SMCodeGen/templates/stateMachineTmpls/state.h.tt>
 ******************************************************/
 
#ifndef __NiDetachWfDetAccptDelSessResp__
#define __NiDetachWfDetAccptDelSessResp__

#include "state.h"

namespace mme {

	class NiDetachWfDetAccptDelSessResp : public SM::State
	{
		public:
			/******************************************
			* Instance 
			*    Creates static instance for the state
			*******************************************/
			static NiDetachWfDetAccptDelSessResp* Instance();

			/****************************************
			* NiDetachWfDetAccptDelSessResp
			*    Destructor
			****************************************/
			~NiDetachWfDetAccptDelSessResp();			
			
			/******************************************
			* initialize
			*  Initializes action handlers for the state
			* and next state
			******************************************/
			void initialize();
	
		private:
			/****************************************
			* NiDetachWfDetAccptDelSessResp
			*    Private constructor
			****************************************/
			NiDetachWfDetAccptDelSessResp();  
	};
};
#endif // __NiDetachWfDetAccptDelSessResp__
