/*
 * Copyright 2020-present Infosys Limited
 *
 * SPDX-License-Identifier: Apache-2.0
 */
 
 /******************************************************
 * niDetachWfDelSessResp.h
 * This is an auto generated file.
 * Please do not edit this file.
 * All edits to be made through template source file
 * <TOP-DIR/scripts/SMCodeGen/templates/stateMachineTmpls/state.h.tt>
 ******************************************************/
 
#ifndef __NiDetachWfDelSessResp__
#define __NiDetachWfDelSessResp__

#include "state.h"

namespace mme {

	class NiDetachWfDelSessResp : public SM::State
	{
		public:
			/******************************************
			* Instance 
			*    Creates static instance for the state
			*******************************************/
			static NiDetachWfDelSessResp* Instance();

			/****************************************
			* NiDetachWfDelSessResp
			*    Destructor
			****************************************/
			~NiDetachWfDelSessResp();			
			
			/******************************************
			* initialize
			*  Initializes action handlers for the state
			* and next state
			******************************************/
			void initialize();
	
		private:
			/****************************************
			* NiDetachWfDelSessResp
			*    Private constructor
			****************************************/
			NiDetachWfDelSessResp();  
	};
};
#endif // __NiDetachWfDelSessResp__
