/*
 * Copyright 2020-present Infosys Limited
 *
 * SPDX-License-Identifier: Apache-2.0
 */
 
 /******************************************************
 * s1HoWfTauCheck.h
 * This is an auto generated file.
 * Please do not edit this file.
 * All edits to be made through template source file
 * <TOP-DIR/scripts/SMCodeGen/templates/stateMachineTmpls/state.h.tt>
 ******************************************************/
 
#ifndef __S1HoWfTauCheck__
#define __S1HoWfTauCheck__

#include "state.h"

namespace mme {

	class S1HoWfTauCheck : public SM::State
	{
		public:
			/******************************************
			* Instance 
			*    Creates static instance for the state
			*******************************************/
			static S1HoWfTauCheck* Instance();

			/****************************************
			* S1HoWfTauCheck
			*    Destructor
			****************************************/
			~S1HoWfTauCheck();			
			
			/******************************************
			* initialize
			*  Initializes action handlers for the state
			* and next state
			******************************************/
			void initialize();
	
		private:
			/****************************************
			* S1HoWfTauCheck
			*    Private constructor
			****************************************/
			S1HoWfTauCheck();  
	};
};
#endif // __S1HoWfTauCheck__
