 /*
 * Copyright 2021-present Infosys Limited
 *
 * SPDX-License-Identifier: Apache-2.0
 */ 
/******************************************************************************
 * mmeTauProcedureCtxtManager.cpp
 * This is an auto generated file.
 * Please do not edit this file.
 * All edits to be made through template source file
 * <TOP-DIR/scripts/SMCodeGen/templates/ctxtManagerTmpls/blockPoolManager.cpp.tt>
 ******************************************************************************/

#include "memPoolManager.h"
#include "contextManager/dataBlocks.h"
#include "contextManager/mmeTauProcedureCtxtManager.h"

using namespace cmn::memPool;

namespace mme
{
	/******************************************************************************
	* Constructor
	******************************************************************************/
	MmeTauProcedureCtxtManager::MmeTauProcedureCtxtManager(int numOfBlocks):poolManager_m(numOfBlocks)
	{
	}
	
	/******************************************************************************
	* Destructor
	******************************************************************************/
	MmeTauProcedureCtxtManager::~MmeTauProcedureCtxtManager()
	{
	}
	
	/******************************************************************************
	* Allocate MmeTauProcedureCtxt data block
	******************************************************************************/
	MmeTauProcedureCtxt* MmeTauProcedureCtxtManager::allocateMmeTauProcedureCtxt()
	{
		MmeTauProcedureCtxt* MmeTauProcedureCtxt_p = poolManager_m.allocate();
		return MmeTauProcedureCtxt_p;
	}
	
	/******************************************************************************
	* Deallocate a MmeTauProcedureCtxt data block
	******************************************************************************/
	void MmeTauProcedureCtxtManager::deallocateMmeTauProcedureCtxt(MmeTauProcedureCtxt* MmeTauProcedureCtxtp )
	{
		poolManager_m.free( MmeTauProcedureCtxtp );
	}
}