 /*
 * Copyright 2019-present Infosys Limited
 *
 * SPDX-License-Identifier: Apache-2.0
 */ 
/******************************************************************************
 * s1HandoverProcedureContextManager.cpp
 * This is an auto generated file.
 * Please do not edit this file.
 * All edits to be made through template source file
 * <TOP-DIR/scripts/SMCodeGen/templates/ctxtManagerTmpls/blockPoolManager.cpp.tt>
 ******************************************************************************/

#include "memPoolManager.h"
#include "contextManager/dataBlocks.h"
#include "contextManager/s1HandoverProcedureContextManager.h"

using namespace cmn::memPool;

namespace mme
{
	/******************************************************************************
	* Constructor
	******************************************************************************/
	S1HandoverProcedureContextManager::S1HandoverProcedureContextManager(int numOfBlocks):poolManager_m(numOfBlocks)
	{
	}
	
	/******************************************************************************
	* Destructor
	******************************************************************************/
	S1HandoverProcedureContextManager::~S1HandoverProcedureContextManager()
	{
	}
	
	/******************************************************************************
	* Allocate S1HandoverProcedureContext data block
	******************************************************************************/
	S1HandoverProcedureContext* S1HandoverProcedureContextManager::allocateS1HandoverProcedureContext()
	{
		S1HandoverProcedureContext* S1HandoverProcedureContext_p = poolManager_m.allocate();
		return S1HandoverProcedureContext_p;
	}
	
	/******************************************************************************
	* Deallocate a S1HandoverProcedureContext data block
	******************************************************************************/
	void S1HandoverProcedureContextManager::deallocateS1HandoverProcedureContext(S1HandoverProcedureContext* S1HandoverProcedureContextp )
	{
		poolManager_m.free( S1HandoverProcedureContextp );
	}
}