 /*
 * Copyright 2021-present Infosys Limited
 *
 * SPDX-License-Identifier: Apache-2.0
 */ 
/******************************************************************************
 * x2HOMmProcedureContextManager.cpp
 * This is an auto generated file.
 * Please do not edit this file.
 * All edits to be made through template source file
 * <TOP-DIR/scripts/SMCodeGen/templates/ctxtManagerTmpls/blockPoolManager.cpp.tt>
 ******************************************************************************/

#include "memPoolManager.h"
#include "contextManager/dataBlocks.h"
#include "contextManager/x2HOMmProcedureContextManager.h"

using namespace cmn::memPool;

namespace mme
{
	/******************************************************************************
	* Constructor
	******************************************************************************/
	X2HOMmProcedureContextManager::X2HOMmProcedureContextManager(int numOfBlocks):poolManager_m(numOfBlocks)
	{
	}
	
	/******************************************************************************
	* Destructor
	******************************************************************************/
	X2HOMmProcedureContextManager::~X2HOMmProcedureContextManager()
	{
	}
	
	/******************************************************************************
	* Allocate X2HOMmProcedureContext data block
	******************************************************************************/
	X2HOMmProcedureContext* X2HOMmProcedureContextManager::allocateX2HOMmProcedureContext()
	{
		X2HOMmProcedureContext* X2HOMmProcedureContext_p = poolManager_m.allocate();
		return X2HOMmProcedureContext_p;
	}
	
	/******************************************************************************
	* Deallocate a X2HOMmProcedureContext data block
	******************************************************************************/
	void X2HOMmProcedureContextManager::deallocateX2HOMmProcedureContext(X2HOMmProcedureContext* X2HOMmProcedureContextp )
	{
		poolManager_m.free( X2HOMmProcedureContextp );
	}
}