 /*
 * Copyright 2019-present, Infosys Limited.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#ifndef __MmeAttachProcedureCtxtManager__
#define __MmeAttachProcedureCtxtManager__
/******************************************************
* mmeAttachProcedureCtxtManager.h
 * This is an auto generated file.
 * Please do not edit this file.
 * All edits to be made through template source file
 * <TOP-DIR/scripts/SMCodeGen/templates/ctxtManagerTmpls/blockPoolManager.h.tt>
 ***************************************/
#include "memPoolManager.h"

namespace mme
{
	class MmeAttachProcedureCtxt;
	class MmeAttachProcedureCtxtManager
	{
		public:
			/****************************************
			* MmeAttachProcedureCtxtManager
			*  constructor
			****************************************/
			MmeAttachProcedureCtxtManager(int numOfBlocks);
			
			/****************************************
			* MmeAttachProcedureCtxtManager
			*    Destructor
			****************************************/
			~MmeAttachProcedureCtxtManager();
			
			/******************************************
			 * allocateMmeAttachProcedureCtxt
			 * allocate MmeAttachProcedureCtxt data block
			 ******************************************/
			MmeAttachProcedureCtxt* allocateMmeAttachProcedureCtxt();
			
			/******************************************
			 * deallocateMmeAttachProcedureCtxt
			 * deallocate a MmeAttachProcedureCtxt data block
			 ******************************************/
			void deallocateMmeAttachProcedureCtxt(MmeAttachProcedureCtxt* MmeAttachProcedureCtxtp );
	
		private:
			cmn::memPool::MemPoolManager<MmeAttachProcedureCtxt> poolManager_m;
	};
};

#endif
		
		