 /*
 * Copyright 2019-present, Infosys Limited.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#ifndef __S1HandoverProcedureContextManager__
#define __S1HandoverProcedureContextManager__
/******************************************************
* s1HandoverProcedureContextManager.h
 * This is an auto generated file.
 * Please do not edit this file.
 * All edits to be made through template source file
 * <TOP-DIR/scripts/SMCodeGen/templates/ctxtManagerTmpls/blockPoolManager.h.tt>
 ***************************************/
#include "memPoolManager.h"

namespace mme
{
	class S1HandoverProcedureContext;
	class S1HandoverProcedureContextManager
	{
		public:
			/****************************************
			* S1HandoverProcedureContextManager
			*  constructor
			****************************************/
			S1HandoverProcedureContextManager(int numOfBlocks);
			
			/****************************************
			* S1HandoverProcedureContextManager
			*    Destructor
			****************************************/
			~S1HandoverProcedureContextManager();
			
			/******************************************
			 * allocateS1HandoverProcedureContext
			 * allocate S1HandoverProcedureContext data block
			 ******************************************/
			S1HandoverProcedureContext* allocateS1HandoverProcedureContext();
			
			/******************************************
			 * deallocateS1HandoverProcedureContext
			 * deallocate a S1HandoverProcedureContext data block
			 ******************************************/
			void deallocateS1HandoverProcedureContext(S1HandoverProcedureContext* S1HandoverProcedureContextp );
	
		private:
			cmn::memPool::MemPoolManager<S1HandoverProcedureContext> poolManager_m;
	};
};

#endif
		
		
