  
/*
 * Copyright 2019-present Infosys Limited
 *
 * SPDX-License-Identifier: Apache-2.0
 */
 
/**************************************
 * detachWfPurgeResp.cpp
 * This is an auto generated file.
 * Please do not edit this file.
 * All edits to be made through template source file
 * <TOP-DIR/scripts/SMCodeGen/templates/stateMachineTmpls/state.cpp.tt>
 **************************************/

#include "mmeSmDefs.h"
#include "actionTable.h"
#include "actionHandlers/actionHandlers.h"

#include "mmeStates/detachWfPurgeResp.h"

using namespace mme;
using namespace SM;

/******************************************************************************
* Constructor
******************************************************************************/
DetachWfPurgeResp::DetachWfPurgeResp():State(detach_wf_purge_resp)
{
}

/******************************************************************************
* Destructor
******************************************************************************/
DetachWfPurgeResp::~DetachWfPurgeResp()
{
}

/******************************************************************************
* creates and returns static instance
******************************************************************************/
DetachWfPurgeResp* DetachWfPurgeResp::Instance()
{
        static DetachWfPurgeResp state;
        return &state;
}

/******************************************************************************
* initializes eventToActionsMap
******************************************************************************/
void DetachWfPurgeResp::initialize()
{
        {
                ActionTable actionTable;
                actionTable.addAction(&ActionHandlers::process_pur_resp);
                actionTable.addAction(&ActionHandlers::detach_accept_to_ue);
                eventToActionsMap.insert(pair<uint16_t, ActionTable>(PURGE_RESP_FROM_HSS, actionTable));
        }
}
