  
/*
 * Copyright 2019-present Infosys Limited
 *
 * SPDX-License-Identifier: Apache-2.0
 */
 
/**************************************
 * niDetachWfDetachAccept.cpp
 * This is an auto generated file.
 * Please do not edit this file.
 * All edits to be made through template source file
 * <TOP-DIR/scripts/SMCodeGen/templates/stateMachineTmpls/state.cpp.tt>
 **************************************/

#include "mmeSmDefs.h"
#include "actionTable.h"
#include "actionHandlers/actionHandlers.h"

#include "mmeStates/niDetachWfDetachAccept.h"	
#include "mmeStates/niDetachWfS1RelComp.h"

using namespace mme;
using namespace SM;

/******************************************************************************
* Constructor
******************************************************************************/
NiDetachWfDetachAccept::NiDetachWfDetachAccept():State(ni_detach_wf_detach_accept)
{
}

/******************************************************************************
* Destructor
******************************************************************************/
NiDetachWfDetachAccept::~NiDetachWfDetachAccept()
{
}

/******************************************************************************
* creates and returns static instance
******************************************************************************/
NiDetachWfDetachAccept* NiDetachWfDetachAccept::Instance()
{
        static NiDetachWfDetachAccept state;
        return &state;
}

/******************************************************************************
* initializes eventToActionsMap
******************************************************************************/
void NiDetachWfDetachAccept::initialize()
{
        {
                ActionTable actionTable;
                actionTable.addAction(&ActionHandlers::process_detach_accept_from_ue);
                actionTable.addAction(&ActionHandlers::send_s1_rel_cmd_to_ue_for_detach);
                actionTable.setNextState(NiDetachWfS1RelComp::Instance());
                eventToActionsMap.insert(pair<uint16_t, ActionTable>(DETACH_ACCEPT_FROM_UE, actionTable));
        }
}
