  
/*
 * Copyright 2019-present Infosys Limited
 *
 * SPDX-License-Identifier: Apache-2.0
 */
 
/**************************************
 * tauWfAia.cpp
 * This is an auto generated file.
 * Please do not edit this file.
 * All edits to be made through template source file
 * <TOP-DIR/scripts/SMCodeGen/templates/stateMachineTmpls/state.cpp.tt>
 **************************************/

#include "mmeSmDefs.h"
#include "actionTable.h"
#include "actionHandlers/actionHandlers.h"

#include "mmeStates/tauWfAia.h"	
#include "mmeStates/tauWfAuthResponse.h"

using namespace mme;
using namespace SM;

/******************************************************************************
* Constructor
******************************************************************************/
TauWfAia::TauWfAia():State(tau_wf_aia)
{
}

/******************************************************************************
* Destructor
******************************************************************************/
TauWfAia::~TauWfAia()
{
}

/******************************************************************************
* creates and returns static instance
******************************************************************************/
TauWfAia* TauWfAia::Instance()
{
        static TauWfAia state;
        return &state;
}

/******************************************************************************
* initializes eventToActionsMap
******************************************************************************/
void TauWfAia::initialize()
{
        {
                ActionTable actionTable;
                actionTable.addAction(&ActionHandlers::process_aia);
                actionTable.addAction(&ActionHandlers::auth_req_to_ue);
                actionTable.setNextState(TauWfAuthResponse::Instance());
                eventToActionsMap.insert(pair<uint16_t, ActionTable>(AIA_FROM_HSS, actionTable));
        }
}
